version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:8.4.0

    steps:
      - checkout
      - restore_cache:
          key: Izetta-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: Izetta-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
      - add_ssh_keys:
          fingerprints:
            - "31:4a:b4:5d:65:d3:6b:be:4e:1a:a1:28:a6:fa:26:45"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "$CIRCLE_BRANCH" == 'master' ]; then
              ./.circleci/setup-heroku.sh
              ./.circleci/setup-retry.sh

              heroku git:remote --app pinemz-izetta
              git push -f heroku master
            fi
